### ISSUE TITLE
There was an error getting information for views_selective_filters

### ISSUE THREAD

**Issue by pnmgman2** [backdrop-contrib/views_selective_filters#1]
These errors appear while installing this module - BD and all other modules updated to latest (1.21.3).
Upon running the install from within BD Install New Module function, these errors appear:

There was an error getting information for views_selective_filters
There was an error getting information for views_selective_filters

The module fails to install.

Any idea of what's going on here?

**Comment by argiepiano** [comment]
I had the same problems. The module is downloaded and can be enabled afterward. These errors may be due to the contrib module records kept by backdropcms.org. 

For the maintainer: Often editing the release and re-releasing will solve these. Otherwise the maintainer will need to be in touch with the people with admin access to backddropcms.org and ask them to edit the record there.

**Comment by laryn** [comment]
I just made a new release which should hopefully fix this. Please reopen if not!
